#Problem can be found at Trywildcard.com

str_list = ["XXXXXXXXXXXXX*X*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX*XXXXXXXXXXXXXXXXXXXXXXXXXXXXX*XXX*XXXX*XX",
"XXXXXXXXXXXXXXXX*XXXXXXXX*XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXX*XXXXXXXXXXXXX**XXX*XX*XX*XX*XXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX*XXXX*XXXXXXXX*XXXXXXXXXX*XXXXXX*XXXXXX",
"XXXXXXXX*XXXXXXXXXXXXX*XXXXX*XXXXX*X**XXXXXXXXXXXX",
"XXXXXXXXXXXX*XXXXXXXXXXXXXXXXXXXXXXXXXXXX*X*XXXXXX",
"XXXX*XXXXXXXX*XXXXXXX**XXXX**XXXXXXXXXXXXXXXXXXXXX",
"**XXXXXXXXXX*XXXXXX*XXXXXXXXXXX*XXXXXXXXXXXXXXXXX*",
"XXXXXXXXXXXXXXXXXX*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXX*XXXXXXXXXXXX*XXXXXXXXXX*XXXXXXXXXXXXXXXXXXX",
"*XXXXXXXXXXXXXXXXXXXX**XX***XX*XXXXXXXXXXXXX*XXXXX",
"XXXXXXXXXXX*XXX**XX*X*XXXX*XXX*X*XXX*XXXXX*XXXXXXX",
"XXXXXXXXXXXXX*XXXXXXXXXX*XXXXX*XXXXXXXXX*XXXXXXXXX",
"XXXXXXXXXXXXXXXXX*XXXXX*XXX*XXXX*XXXXXXXXX*XXXXXXX",
"XXXXXXXX*X*XXXXXXX*XXXXXXXXXXXXXXX*X*XXXX*XX*XXXXX",
"XXXXXXXXX*X*XXXXX*XXXXXX**XXXXXXXXXX*XX*XXXXXXX*XX",
"XXXXXXXXXXXXXXXX**XX*XX*XXXXXXXXXXXXXX*XXXXXXXXXXX",
"XXXXXXX**XXX*XXXXXXXXXXXXX*XXXXXXXXXXXXXX*XXXXXXXX",
"XXXX*XXX*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX*XXXXXXXXX**XXXXX*XXXXXXXXXX*XXXXXX*XXXXX",
"XXXXXX*XXX**XXXXXXXXXX*XX*XXX*XXXXXXXXXXXX*XXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXX*XXXXXX*XX*XXXXXXX***XXXXXXXXXXXXXXXXXXXX*XXXX",
"XX**XXXXXXXXXXXXXXXX**X*XXXXX*XXXXXXXXX*XXXXXXXXXX",
"*X*XXXXXXXX**X*XXXXXXXXX*XXXXXXXXXXX*XXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"*XXXXXXX*XXXXXXXXXXXXX**XXXXXXX*XXXX*XXX*XXXXXXXXX",
"X*XXXXXXXXXXX*XXXXXX*XXXXXXX**X*XX*XXXXXXXXXXXXXX*",
"XXXXXXXXXXXXXXXXXX**XXXXXXXXXXX*XXXXXXXXX*XX*X*XXX",
"XXXXXXXXX*XXXXXXXXX*XXXXXXXXXXXXXX*XXXXXXXX*XX*X*X",
"XXXXXXXXXXXXXXXXXX*XXXX*XXX*XXXX*XXXXXXXXXXX*XXX*X",
"XXXXXXXXXXX*XXXXX*XXXXXX*XXX*XXXXXXXXXXXXXXXXXXXXX",
"X*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX**XXXXXXX",
"XXXXXXXXX*X*XXXX*XXXXXXXXXXXXXXXXXXXXXXXXX*X*XXXXX",
"XXX*XXXXXXXXXXXXX*XXXXXXXXXXX*XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXX*XX*XXXX*XXXXXXXXXXXXX*XXXXX*X*XXXX*XXXX",
"X*XX*XXX*X*XXXXXXXXXXXXXXXXXXXX*XXXXXXXXXXXXXXXXXX",
"XXXXXXXXXX*XXXXXXXXXXXXXXXXXXXXXXXX*XXXXXX**XXXXXX",
"**XXXXXXXXXXX*XXXXXXXXXXXXX*XXXXXXXXXXXX*XXXXX*XXX",
"X*XXXXXXXXXXXXXXXXXXXXXXXXXXXX*XX**XXXXX*XXXXXXXXX",
"XXXXXXXXXXXXXX*XXX*XXXXXXXXX*XXXXXXXX**XXXXXXX*XXX",
"XXXXXXXXXX*XXXXXXXXXXXXXXX*X*XXXXXXXXXXXXXXXX*XXXX",
"XXXXXXXXXXX*XXXX*XXXXXXXXXXXX*XXXX*XXXXXXXXX*XXXXX",
"XXXXXXXXXXXXX*XXXXXXXXXXXXX*XXXX*XXXX*XXXXXXXXXXXX",
"XXXXXXXXXXX*XXXXX*XXXXXXXXXXXX*XXXXXXXXXXXX*XXXX*X",
"XXXXXXX*XXXXXXXXXXXXXXXX*XX*XXXXXXXX*XXXXXXXXXXXXX",
"XXXXXX*XXX*XXXXXXXXXXXXXXXXXXXXXXXXXX*XXXXXXX*XXXX",
"XXXXX*XXXXXXXX*XXXXX*X*XXXXXXXXXXXXX*XX*XXXXXXX**X"]
row_count = []
column_count = []
twodlist = []     #Two Dimensional list for column_count
comboCounts = 0   #Final Count

#initializes the two lists
for element in str_list:
    row_count.append(0)
    column_count.append(0)

#initializes the two dimensional list
for element in str_list:
    new_element = list(element)
    twodlist.append(new_element)

#counting the rows with more than five slots
for index in range (0, len(str_list)):
    row_count[index] = str_list[index].count("*")

#counting the columns with more than five slots
for element in twodlist:
    for j in range(0, len(element)):
        if element[j] == "*":
            column_count[j] = column_count[j] + 1

#Adding up the comboCounts
for element in row_count + column_count:
    if element == 5:
        comboCounts = comboCounts + 120
    elif element == 6:
        comboCounts = comboCounts + 720
    elif element == 7:
        comboCounts = comboCounts + 2520
    elif element == 8:
        comboCounts = comboCounts + 6720
    elif element == 9:
        comboCounts = comboCounts + 15120
    elif element == 10:
        comboCounts = comboCounts + 30240

#result
print comboCounts
